### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by rossabaker** [typelevel/vault#231]
@ScalaWilliam reported to me a while back that the site is down.  Now I'm seeing it, but not the styling.  Might have a bad base URI or something.  I think we did an inelegant migration from tut.

**Comment by rossabaker** [comment]
After #249, I think the problem is that https://typelevel.org/vault/css/light-style.css is 404ing.  This might be a mismatch in template config and microsites version.  I bet we merged a breaking change of the plugin and didn't change the config accordingly.

**Comment by armanbilge** [comment]
Fixed as of the least release: https://typelevel.org/vault/
