### ISSUE TITLE
New release (3.1.1?)

### ISSUE THREAD

**Issue by armanbilge** [typelevel/vault#400]
Probably there aren't any significant changes here, but a "tooling upgrade" release would be helpful.

I'm trying to get rid of the manually configured Scaladoc API mappings in http4s:
https://github.com/http4s/http4s/blob/90f0b08ba1a16c4a688a742df0361a6660b3018d/project/ScaladocApiMapping.scala

To do so, we need Vault to publish with its `apiURL` added to the POM. sbt-typelevel does this automatically, so it just needs a new release (the last one was before sbt-typelevel).

Thanks!

**Comment by rossabaker** [comment]
Drafted here: https://github.com/typelevel/vault/releases/edit/untagged-507c1794867044d48dd7

It ought to be minor due to a Scala.js bump.  We should revert that (weird since 2.x has it), or bite the Scala 3.1 bullet.  I'm fine doing the latter.

**Comment by rossabaker** [comment]
v3.2.0 is cooking.

**Comment by armanbilge** [comment]
Woops, this one failed 🤦

**Comment by rossabaker** [comment]
I'll do it again when I'm back from soccer.

**Comment by rossabaker** [comment]
v3.2.1 is baking.
