### ISSUE TITLE
feature request: expose size of the internal Map

### ISSUE THREAD

**Issue by chenharryhua** [typelevel/vault#441]
Vault defined as:
```final class Vault private (private val m: Map[Unique.Token, Locker])```
is it possible to know the size of m?

Thank you.

**Comment by rossabaker** [comment]
I don't see a reason this couldn't be added, but I'm curious what the use case is.  We don't want to add things without good reason, as every addition constrains future refactoring.

**Comment by chenharryhua** [comment]
I just want to know, at runtime, how many items in the vault. for debug, I can see if my app allocate too many lockers. and also I can apply some logic to decide whether the app can allow more locker to be added.

**Comment by rossabaker** [comment]
Ah, interesting.  I usually use Vault with a fixed set of keys, but that seems reasonable.  Would you like to try a PR?

**Comment by chenharryhua** [comment]
yes. of course. i will give it a shot. thanks.

**Comment by chenharryhua** [comment]
thank you very much. I close the issue.

**Comment by rossabaker** [comment]
Sorry, forgot to mention, this is released as 3.4.0.  Thanks for the contribution!
